### ISSUE TITLE
Initial Documentation

### ISSUE THREAD

**Issue by vidartf** [vidartf/hyperspyUI#22]
Setup and create documentation.

### TODO:
 - [ ] Setup doc system
 - [ ] System for including "Core" plugins' docs
 - [ ] Document:
  - [ ] Quick-start guide
  - [ ] UI build-up: Actions (menu/toolbars), Widgets, Figures/Signals
  - [ ] Data tree
  - [ ] Plugin system
  - [ ] Settings
  - [ ] Loading/saving data
 - [ ] Individual plugins documentation
